module.exports.enums = {
  VisualClass: {
      StaticGray: 0,
      GrayScale: 1,
      StaticColor: 2,
      PseudoColor: 3,
      TrueColor: 4,
      DirectColor: 5,
  },
  EventMask: {
      NoEvent: 0,
      KeyPress: 1,
      KeyRelease: 2,
      ButtonPress: 4,
      ButtonRelease: 8,
      EnterWindow: 16,
      LeaveWindow: 32,
      PointerMotion: 64,
      PointerMotionHint: 128,
      Button1Motion: 256,
      Button2Motion: 512,
      Button3Motion: 1024,
      Button4Motion: 2048,
      Button5Motion: 4096,
      ButtonMotion: 8192,
      KeymapState: 16384,
      Exposure: 32768,
      VisibilityChange: 65536,
      StructureNotify: 131072,
      ResizeRedirect: 262144,
      SubstructureNotify: 524288,
      SubstructureRedirect: 1048576,
      FocusChange: 2097152,
      PropertyChange: 4194304,
      ColorMapChange: 8388608,
      OwnerGrabButton: 16777216,
  },
  BackingStore: {
      NotUseful: 0,
      WhenMapped: 1,
      Always: 2,
  },
  ImageOrder: {
      LSBFirst: 0,
      MSBFirst: 1,
  },
  ModMask: {
      Shift: 1,
      Lock: 2,
      Control: 4,
      1: 8,
      2: 16,
      3: 32,
      4: 64,
      5: 128,
      Any: 32768,
  },
  KeyButMask: {
      Shift: 1,
      Lock: 2,
      Control: 4,
      Mod1: 8,
      Mod2: 16,
      Mod3: 32,
      Mod4: 64,
      Mod5: 128,
      Button1: 256,
      Button2: 512,
      Button3: 1024,
      Button4: 2048,
      Button5: 4096,
  },
  Window: {
      None: 0,
  },
  ButtonMask: {
      1: 256,
      2: 512,
      3: 1024,
      4: 2048,
      5: 4096,
      Any: 32768,
  },
  Motion: {
      Normal: 0,
      Hint: 1,
  },
  NotifyDetail: {
      Ancestor: 0,
      Virtual: 1,
      Inferior: 2,
      Nonlinear: 3,
      NonlinearVirtual: 4,
      Pointer: 5,
      PointerRoot: 6,
      None: 7,
  },
  NotifyMode: {
      Normal: 0,
      Grab: 1,
      Ungrab: 2,
      WhileGrabbed: 3,
  },
  Visibility: {
      Unobscured: 0,
      PartiallyObscured: 1,
      FullyObscured: 2,
  },
  Place: {
      OnTop: 0,
      OnBottom: 1,
  },
  Property: {
      NewValue: 0,
      Delete: 1,
  },
  Time: {
      CurrentTime: 0,
  },
  Atom: {
      None: 0,
      Any: 0,
      PRIMARY: 1,
      SECONDARY: 2,
      ARC: 3,
      ATOM: 4,
      BITMAP: 5,
      CARDINAL: 6,
      COLORMAP: 7,
      CURSOR: 8,
      CUT_BUFFER0: 9,
      CUT_BUFFER1: 10,
      CUT_BUFFER2: 11,
      CUT_BUFFER3: 12,
      CUT_BUFFER4: 13,
      CUT_BUFFER5: 14,
      CUT_BUFFER6: 15,
      CUT_BUFFER7: 16,
      DRAWABLE: 17,
      FONT: 18,
      INTEGER: 19,
      PIXMAP: 20,
      POINT: 21,
      RECTANGLE: 22,
      RESOURCE_MANAGER: 23,
      RGB_COLOR_MAP: 24,
      RGB_BEST_MAP: 25,
      RGB_BLUE_MAP: 26,
      RGB_DEFAULT_MAP: 27,
      RGB_GRAY_MAP: 28,
      RGB_GREEN_MAP: 29,
      RGB_RED_MAP: 30,
      STRING: 31,
      VISUALID: 32,
      WINDOW: 33,
      WM_COMMAND: 34,
      WM_HINTS: 35,
      WM_CLIENT_MACHINE: 36,
      WM_ICON_NAME: 37,
      WM_ICON_SIZE: 38,
      WM_NAME: 39,
      WM_NORMAL_HINTS: 40,
      WM_SIZE_HINTS: 41,
      WM_ZOOM_HINTS: 42,
      MIN_SPACE: 43,
      NORM_SPACE: 44,
      MAX_SPACE: 45,
      END_SPACE: 46,
      SUPERSCRIPT_X: 47,
      SUPERSCRIPT_Y: 48,
      SUBSCRIPT_X: 49,
      SUBSCRIPT_Y: 50,
      UNDERLINE_POSITION: 51,
      UNDERLINE_THICKNESS: 52,
      STRIKEOUT_ASCENT: 53,
      STRIKEOUT_DESCENT: 54,
      ITALIC_ANGLE: 55,
      X_HEIGHT: 56,
      QUAD_WIDTH: 57,
      WEIGHT: 58,
      POINT_SIZE: 59,
      RESOLUTION: 60,
      COPYRIGHT: 61,
      NOTICE: 62,
      FONT_NAME: 63,
      FAMILY_NAME: 64,
      FULL_NAME: 65,
      CAP_HEIGHT: 66,
      WM_CLASS: 67,
      WM_TRANSIENT_FOR: 68,
  },
  ColormapState: {
      Uninstalled: 0,
      Installed: 1,
  },
  Colormap: {
      None: 0,
  },
  Mapping: {
      Modifier: 0,
      Keyboard: 1,
      Pointer: 2,
  },
  WindowClass: {
      CopyFromParent: 0,
      InputOutput: 1,
      InputOnly: 2,
  },
  CW: {
      BackPixmap: 1,
      BackPixel: 2,
      BorderPixmap: 4,
      BorderPixel: 8,
      BitGravity: 16,
      WinGravity: 32,
      BackingStore: 64,
      BackingPlanes: 128,
      BackingPixel: 256,
      OverrideRedirect: 512,
      SaveUnder: 1024,
      EventMask: 2048,
      DontPropagate: 4096,
      Colormap: 8192,
      Cursor: 16384,
  },
  BackPixmap: {
      None: 0,
      ParentRelative: 1,
  },
  Gravity: {
      BitForget: 0,
      WinUnmap: 0,
      NorthWest: 1,
      North: 2,
      NorthEast: 3,
      West: 4,
      Center: 5,
      East: 6,
      SouthWest: 7,
      South: 8,
      SouthEast: 9,
      Static: 10,
  },
  MapState: {
      Unmapped: 0,
      Unviewable: 1,
      Viewable: 2,
  },
  SetMode: {
      Insert: 0,
      Delete: 1,
  },
  ConfigWindow: {
      X: 1,
      Y: 2,
      Width: 4,
      Height: 8,
      BorderWidth: 16,
      Sibling: 32,
      StackMode: 64,
  },
  StackMode: {
      Above: 0,
      Below: 1,
      TopIf: 2,
      BottomIf: 3,
      Opposite: 4,
  },
  Circulate: {
      RaiseLowest: 0,
      LowerHighest: 1,
  },
  PropMode: {
      Replace: 0,
      Prepend: 1,
      Append: 2,
  },
  GetPropertyType: {
      Any: 0,
  },
  SendEventDest: {
      PointerWindow: 0,
      ItemFocus: 1,
  },
  GrabMode: {
      Sync: 0,
      Async: 1,
  },
  GrabStatus: {
      Success: 0,
      AlreadyGrabbed: 1,
      InvalidTime: 2,
      NotViewable: 3,
      Frozen: 4,
  },
  Cursor: {
      None: 0,
  },
  ButtonIndex: {
      Any: 0,
      1: 1,
      2: 2,
      3: 3,
      4: 4,
      5: 5,
  },
  Grab: {
      Any: 0,
  },
  Allow: {
      AsyncPointer: 0,
      SyncPointer: 1,
      ReplayPointer: 2,
      AsyncKeyboard: 3,
      SyncKeyboard: 4,
      ReplayKeyboard: 5,
      AsyncBoth: 6,
      SyncBoth: 7,
  },
  InputFocus: {
      None: 0,
      PointerRoot: 1,
      Parent: 2,
      FollowKeyboard: 3,
  },
  FontDraw: {
      LeftToRight: 0,
      RightToLeft: 1,
  },
  GC: {
      Function: 1,
      PlaneMask: 2,
      Foreground: 4,
      Background: 8,
      LineWidth: 16,
      LineStyle: 32,
      CapStyle: 64,
      JoinStyle: 128,
      FillStyle: 256,
      FillRule: 512,
      Tile: 1024,
      Stipple: 2048,
      TileStippleOriginX: 4096,
      TileStippleOriginY: 8192,
      Font: 16384,
      SubwindowMode: 32768,
      GraphicsExposures: 65536,
      ClipOriginX: 131072,
      ClipOriginY: 262144,
      ClipMask: 524288,
      DashOffset: 1048576,
      DashList: 2097152,
      ArcMode: 4194304,
  },
  GX: {
      clear: 0,
      and: 1,
      andReverse: 2,
      copy: 3,
      andInverted: 4,
      noop: 5,
      xor: 6,
      or: 7,
      nor: 8,
      equiv: 9,
      invert: 10,
      orReverse: 11,
      copyInverted: 12,
      orInverted: 13,
      nand: 14,
      set: 15,
  },
  LineStyle: {
      Solid: 0,
      OnOffDash: 1,
      DoubleDash: 2,
  },
  CapStyle: {
      NotLast: 0,
      Butt: 1,
      Round: 2,
      Projecting: 3,
  },
  JoinStyle: {
      Miter: 0,
      Round: 1,
      Bevel: 2,
  },
  FillStyle: {
      Solid: 0,
      Tiled: 1,
      Stippled: 2,
      OpaqueStippled: 3,
  },
  FillRule: {
      EvenOdd: 0,
      Winding: 1,
  },
  SubwindowMode: {
      ClipByChildren: 0,
      IncludeInferiors: 1,
  },
  ArcMode: {
      Chord: 0,
      PieSlice: 1,
  },
  ClipOrdering: {
      Unsorted: 0,
      YSorted: 1,
      YXSorted: 2,
      YXBanded: 3,
  },
  CoordMode: {
      Origin: 0,
      Previous: 1,
  },
  PolyShape: {
      Complex: 0,
      Nonconvex: 1,
      Convex: 2,
  },
  ImageFormat: {
      XYBitmap: 0,
      XYPixmap: 1,
      ZPixmap: 2,
  },
  ColormapAlloc: {
      None: 0,
      All: 1,
  },
  ColorFlag: {
      Red: 1,
      Green: 2,
      Blue: 4,
  },
  Pixmap: {
      None: 0,
  },
  Font: {
      None: 0,
  },
  QueryShapeOf: {
      LargestCursor: 0,
      FastestTile: 1,
      FastestStipple: 2,
  },
  KB: {
      KeyClickPercent: 1,
      BellPercent: 2,
      BellPitch: 4,
      BellDuration: 8,
      Led: 16,
      LedMode: 32,
      Key: 64,
      AutoRepeatMode: 128,
  },
  LedMode: {
      Off: 0,
      On: 1,
  },
  AutoRepeatMode: {
      Off: 0,
      On: 1,
      Default: 2,
  },
  Blanking: {
      NotPreferred: 0,
      Preferred: 1,
      Default: 2,
  },
  Exposures: {
      NotAllowed: 0,
      Allowed: 1,
      Default: 2,
  },
  HostMode: {
      Insert: 0,
      Delete: 1,
  },
  Family: {
      Internet: 0,
      DECnet: 1,
      Chaos: 2,
      ServerInterpreted: 5,
      Internet6: 6,
  },
  AccessControl: {
      Disable: 0,
      Enable: 1,
  },
  CloseDown: {
      DestroyAll: 0,
      RetainPermanent: 1,
      RetainTemporary: 2,
  },
  Kill: {
      AllTemporary: 0,
  },
  ScreenSaver: {
      Reset: 0,
      Active: 1,
  },
  MappingStatus: {
      Success: 0,
      Busy: 1,
      Failure: 2,
  },
  MapIndex: {
      Shift: 0,
      Lock: 1,
      Control: 2,
      1: 3,
      2: 4,
      3: 5,
      4: 6,
      5: 7,
  },
}