module.exports.event = {
  Error: 0,
  Reply: 1,
  KeyPress: 2,
  KeyRelease: 3,
  ButtonPress: 4,
  ButtonRelease: 5,
  MotionNotify: 6,
  EnterNotify: 7,
  LeaveNotify: 8,
  FocusIn: 9,
  FocusOut: 10,
  KeymapNotify: 11,
  Expose: 12,
  GraphicsExposure: 13,
  NoExposure: 14,
  VisibilityNotify: 15,
  CreateNotify: 16,
  DestroyNotify: 17,
  UnmapNotify: 18,
  MapNotify: 19,
  MapRequest: 20,
  ReparentNotify: 21,
  ConfigureNotify: 22,
  ConfigureRequest: 23,
  GravityNotify: 24,
  ResizeRequest: 25,
  CirculateNotify: 26,
  CirculateRequest: 27,
  PropertyNotify: 28,
  SelectionClear: 29,
  SelectionRequest: 30,
  SelectionNotify: 31,
  ColormapNotify: 32,
  ClientMessage: 33,
  MappingNotify: 34,
  GenericEvent: 35,

  names: [
    "Error", "Reply", "KeyPress", "KeyRelease",
    "ButtonPress", "ButtonRelease", "MotionNotify", "EnterNotify",
    "LeaveNotify", "FocusIn", "FocusOut", "KeymapNotify",
    "Expose", "GraphicsExpose", "NoExpose", "VisibilityNotify",
    "CreateNotify", "DestroyNotify", "UnmapNotify",
    "MapNotify", "MapRequest", "ReparentNotify", "ConfigureNotify",
    "ConfigureRequest", "GravityNotify", "ResizeRequest",
    "CirculateNotify", "CirculateRequest", "PropertyNotify",
    "SelectionClear", "SelectionRequest", "SelectionNotify",
    "ColormapNotify", "ClientMessage", "MappingNotify", "GenericEvent"
  ],

  template: {
    Error: ['C code', 'S seq', 'L bad_value', 'C minor_opcode', 'S major_opcode'],
  KeyPress: ['C detail', 'S seq','L time', 'L root', 'L event', 'L child', 's root_x', 's root_y', 's event_x', 's event_y', 'S state', 'C same_screen', ],
  KeyRelease: ['C detail', 'S seq','L time', 'L root', 'L event', 'L child', 's root_x', 's root_y', 's event_x', 's event_y', 'S state', 'C same_screen', ],
  ButtonPress: ['C detail', 'S seq','L time', 'L root', 'L event', 'L child', 's root_x', 's root_y', 's event_x', 's event_y', 'S state', 'C same_screen', ],
  ButtonRelease: ['C detail', 'S seq','L time', 'L root', 'L event', 'L child', 's root_x', 's root_y', 's event_x', 's event_y', 'S state', 'C same_screen', ],
  MotionNotify: ['C detail', 'S seq','L time', 'L root', 'L event', 'L child', 's root_x', 's root_y', 's event_x', 's event_y', 'S state', 'C same_screen', ],
  EnterNotify: ['C detail', 'S seq','L time', 'L root', 'L event', 'L child', 's root_x', 's root_y', 's event_x', 's event_y', 'S state', 'C mode', 'C same_screen_focus', ],
  LeaveNotify: ['C detail', 'S seq','L time', 'L root', 'L event', 'L child', 's root_x', 's root_y', 's event_x', 's event_y', 'S state', 'C mode', 'C same_screen_focus', ],
  FocusIn: ['C detail', 'S seq','L event', 'C mode', ],
  FocusOut: ['C detail', 'S seq','L event', 'C mode', ],
  KeymapNotify: [' keys', ],
  Expose: ['x undefined', 'S seq','L window', 'S x', 'S y', 'S width', 'S height', 'S count', ],
  GraphicsExposure: ['x undefined', 'S seq','L drawable', 'S x', 'S y', 'S width', 'S height', 'S minor_opcode', 'S count', 'C major_opcode', ],
  NoExposure: ['x undefined', 'S seq','L drawable', 'S minor_opcode', 'C major_opcode', ],
  VisibilityNotify: ['x undefined', 'S seq','L window', 'C state', ],
  CreateNotify: ['x undefined', 'S seq','L parent', 'L window', 's x', 's y', 'S width', 'S height', 'S border_width', 'C override_redirect', ],
  DestroyNotify: ['x undefined', 'S seq','L event', 'L window', ],
  UnmapNotify: ['x undefined', 'S seq','L event', 'L window', 'C from_configure', ],
  MapNotify: ['x undefined', 'S seq','L event', 'L window', 'C override_redirect', ],
  MapRequest: ['x undefined', 'S seq','L parent', 'L window', ],
  ReparentNotify: ['x undefined', 'S seq','L event', 'L window', 'L parent', 's x', 's y', 'C override_redirect', ],
  ConfigureNotify: ['x undefined', 'S seq','L event', 'L window', 'L above_sibling', 's x', 's y', 'S width', 'S height', 'S border_width', 'C override_redirect', ],
  ConfigureRequest: ['C stack_mode', 'S seq','L parent', 'L window', 'L sibling', 's x', 's y', 'S width', 'S height', 'S border_width', 'S value_mask', ],
  GravityNotify: ['x undefined', 'S seq','L event', 'L window', 's x', 's y', ],
  ResizeRequest: ['x undefined', 'S seq','L window', 'S width', 'S height', ],
  CirculateNotify: ['x undefined', 'S seq','L event', 'L window', 'xxxx undefined', 'C place', ],
  CirculateRequest: ['x undefined', 'S seq','L event', 'L window', 'xxxx undefined', 'C place', ],
  PropertyNotify: ['x undefined', 'S seq','L window', 'L atom', 'L time', 'C state', ],
  SelectionClear: ['x undefined', 'S seq','L time', 'L owner', 'L selection', ],
  SelectionRequest: ['x undefined', 'S seq','L time', 'L owner', 'L requestor', 'L selection', 'L target', 'L property', ],
  SelectionNotify: ['x undefined', 'S seq','L time', 'L requestor', 'L selection', 'L target', 'L property', ],
  ColormapNotify: ['x undefined', 'S seq','L window', 'L colormap', 'C _new', 'C state', ],
  ClientMessage: ['C format', 'S seq','L window', 'L type', 'undefined data', ],
  MappingNotify: ['x undefined', 'S seq','C request', 'C first_keycode', 'C count', ],
  }
}